obstacle_range: 10
raytrace_range: 10
max_obstacle_height: 2.0
inf_is_valid: true
footprint: [[0.01, 0.01], [-0.01, 0.01], [-0.01, -0.01], [0.01, -0.01]]

inflation_radius: 0.0
costscalingfactor: 1.3

map_topic: map
subscribe_to_updates: true
observation_sources: stereo_camera
stereo_camera: {sensor_frame: camera_link, data_type: PointCloud2, topic: stereo/points2, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
