planners:
  - name: TestGlobalPlanner
    type: global_planner/TestGlobalPlanner

controllers:
  - name: DWAPlannerROS
    type: local_planner/TestLocalPlanner

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2