obstacle_range: 10
raytrace_range: 10
max_obstacle_height: 2.0
inf_is_valid: true
footprint: [[0.01, 0.01], [-0.01, 0.01], [-0.01, -0.01], [0.01, -0.01]]

inflation_radius: 0.0
costscalingfactor: 1.3

map_topic: /map
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
