TebLocalPlannerROS:

    odom_topic: /odom
    map_frame: map

    # Trajectory
    teb_autosize: True
    dt_ref: 0.3
    dt_hysteresis: 0.03
    global_plan_overwrite_orientation: True
    max_global_plan_lookahead_dist: 0
    feasibility_check_no_poses: 10

    # Robot

    max_vel_x: 1
    max_vel_x_backwards: 0.1
    max_vel_y: 0.0
    max_vel_theta: 1
    acc_lim_x: 0.5
    acc_lim_theta: 0.5
    min_turning_radius: 0.0

    footprint_model:
      type: "circular"
      radius: 0.2

    # GoalTolerance

    xy_goal_tolerance: 0.4
    yaw_goal_tolerance: 3.14
    free_goal_vel: False

    # Obstacles

    inflation_dist: 1.0
    min_obstacle_dist: 0.4
    include_costmap_obstacles: True
    costmap_obstacles_behind_robot_dist: 1.0
    obstacle_poses_affected: 30
    costmap_converter_plugin: ""
    costmap_converter_spin_thread: True
    costmap_converter_rate: 5

    # Optimization

    no_inner_iterations: 5
    no_outer_iterations: 4
    optimization_activate: True
    optimization_verbose: False
    penalty_epsilon: 0.05
    weight_max_vel_x: 4
    weight_max_vel_theta: 1
    weight_acc_lim_x: 1
    weight_acc_lim_theta: 1
    weight_kinematics_nh: 100
    weight_kinematics_forward_drive: 1
    weight_kinematics_turning_radius: 1
    weight_optimaltime: 1
    weight_obstacle: 50
    weight_dynamic_obstacle: 10 # not in use yet
    global_plan_viapoint_sep: 0.3

    # Homotopy Class Planner

    enable_homotopy_class_planning: False
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 2
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 5
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: True
